version: '3.8'
services:
  app:
    container_name: microsvc-dd
    image: bankierubybank/microsvc-dd:latest
    build:
      context: ./tarot
      dockerfile: Dockerfile
      args:
        CIRunNumber: 'local-build'
    deploy:
      restart_policy:
        condition: unless-stopped
    ports:
      - 8080:8080
    environment:
      # Service configuration
      PORT: 8080
      NAMESPACE: 'N/A'
      NODENAME: 'local'
      # OpenTelemetry configuration
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://localhost:4318'
      SERVICE_NAME: 'tarot-api'
      INSECURE_MODE: true
