apiVersion: v1
kind: Service
metadata:
  name: tarot-api-svc
  labels:
    app: tarot-api
spec:
  selector:
    app: tarot-api
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: None
