basePath: /api/v1
definitions:
  models.TarotModel:
    description: Tarot Model
    properties:
      cardname:
        example: The Fool
        maxLength: 255
        type: string
      number:
        example: "0"
        maxLength: 15
        type: string
      type:
        example: major
        maxLength: 63
        type: string
    required:
    - cardname
    - number
    - type
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample API for learning microservices
  title: Microsvc-dd
  version: 0.1.0-rc
paths:
  /debug:
    get:
      consumes:
      - application/json
      description: Get debug information
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get debug information
      tags:
      - debug
  /tarots/:
    get:
      consumes:
      - application/json
      description: Get all tarot cards
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TarotModel'
            type: array
      summary: Get all tarot cards
      tags:
      - tarot
  /tarots/{cardnumber}:
    get:
      consumes:
      - application/json
      description: Get a tarot card by ID
      parameters:
      - description: Tarot ID
        in: path
        name: cardnumber
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TarotModel'
      summary: Get a tarot card by ID
      tags:
      - tarot
  /tarots/random:
    get:
      consumes:
      - application/json
      description: Get a random tarot card
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TarotModel'
      summary: Get a random tarot card
      tags:
      - tarot
swagger: "2.0"
