name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: fs
          scan-ref: "."
          scanners: vuln,secret,misconfig,license # optional, default is vuln,secret
        continue-on-error: true
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  build:
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set image tag
        id: set-image-tag
        run: echo "IMAGE_TAG=$([[ ${{ github.ref }} == 'refs/heads/main' ]] && echo '${{ github.run_number }}' || echo 'dev')" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build ./tarot --file ./tarot/Dockerfile --tag my-image-name:${{ env.IMAGE_TAG }}
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: image
          image-ref: "my-image-name:${{ env.IMAGE_TAG }}"
          ignore-unfixed: true # optional, default is false
          severity: HIGH,CRITICAL # optional, default is UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
        continue-on-error: true
      - name: Push image to registry (Docker Hub)
        run: echo "Pushing my-image-name:${{ env.IMAGE_TAG }} to Docker Hub"
